function database(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => { const request = indexedDB.open('director-media-v1', 1); request.onupgradeneeded = () => request.result.createObjectStore('takes', { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
}
export type Take = { id: string; shotId: string; workflowId: string; name: string; blob: Blob; createdAt: number; approved: boolean; duration: number; provider: string; inEdit?: boolean; editOrder?: number; inPoint?: number; outPoint?: number };
export async function saveTake(take: Take) { const db = await database(); try { await new Promise<void>((resolve, reject) => { const tx = db.transaction('takes', 'readwrite'); tx.objectStore('takes').put(take); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error || new Error('Không lưu được video')); }); } finally { db.close(); } }
export async function listTakes(workflowId: string): Promise<Take[]> { const db = await database(); try { const all = await new Promise<Take[]>((resolve, reject) => { const r = db.transaction('takes').objectStore('takes').getAll(); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); return all.filter(t => t.workflowId === workflowId).sort((a, b) => b.createdAt - a.createdAt); } finally { db.close(); } }
export async function deleteTake(id: string) { const db = await database(); try { await new Promise<void>((resolve, reject) => { const tx = db.transaction('takes', 'readwrite'); tx.objectStore('takes').delete(id); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); } finally { db.close(); } }
export async function patchTake(id: string, patch: Partial<Take>) { const db = await database(); try { await new Promise<void>((resolve, reject) => { const tx = db.transaction('takes', 'readwrite'), store = tx.objectStore('takes'), get = store.get(id); get.onsuccess = () => { if (!get.result) { tx.abort(); return; } store.put({ ...get.result, ...patch, id }); }; tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); tx.onabort = () => reject(new Error('Take không tồn tại hoặc không lưu được')); }); } finally { db.close(); } }
export async function imageForApi(blob: Blob): Promise<string> {
  if (!['image/png', 'image/jpeg'].includes(blob.type) || blob.size > 15000000) throw new Error('Ảnh đầu cảnh phải là PNG/JPEG, tối đa 15 MB');
  const bitmap = await createImageBitmap(blob);
  try { const scale = Math.min(1, 1920 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale); canvas.getContext('2d')!.drawImage(bitmap, 0, 0, canvas.width, canvas.height); const data = canvas.toDataURL('image/jpeg', .86); if (data.length > 3500000) throw new Error('Ảnh vẫn quá lớn sau nén, chọn ảnh nhỏ hơn'); return data; } finally { bitmap.close(); }
}
export async function videoDuration(blob: Blob): Promise<number> { const url = URL.createObjectURL(blob), v = document.createElement('video'); try { return await new Promise<number>((resolve, reject) => { v.onloadedmetadata = () => Number.isFinite(v.duration) && v.duration > 0 ? resolve(v.duration) : reject(new Error('Video không có thời lượng hợp lệ')); v.onerror = () => reject(new Error('Trình duyệt không đọc được video')); v.src = url; }); } finally { v.removeAttribute('src'); v.load(); URL.revokeObjectURL(url); } }
export function downloadBlob(name: string, blob: Blob) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }
