import { useEffect, useMemo, useRef, useState } from 'react';
import { compileWorkflow, parseWorkflow, updatePrompt, workflowHandoff, type Workflow } from '../shared/workflow';
import { callStudio, getApiSession } from './providerClient';
import { deleteTake, downloadBlob, imageForApi, listTakes, patchTake, saveTake, videoDuration, type Take } from './mediaStore';
import { renderMovie } from './browserRender';
import { buildEditPlan } from '../shared/editPlan';
const WORKFLOW_KEY = 'director-workflow-v1', JOB_KEY = 'director-video-jobs-v1';
type Job = { id: string; workflowId: string; shotId: string; operation: string; model: string; prompt: string; createdAt: number; done?: boolean; uri?: string | null };
function readJobs(): Job[] { try { return JSON.parse(localStorage.getItem(JOB_KEY) || '[]'); } catch { return []; } }
function TakeCard({ take, onUpdate }: { take: Take; onUpdate: () => void }) {
  const [url, setUrl] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const value = URL.createObjectURL(take.blob); setUrl(value); return () => URL.revokeObjectURL(value); }, [take.blob]);
  async function action(fn: () => Promise<void>) { try { await fn(); onUpdate(); } catch (e) { setError((e as Error).message); } }
  return <div className="cinema-take"><video controls src={url || undefined} preload="metadata" /><strong>{take.name}</strong><span>{take.duration.toFixed(1)} giây · {take.provider}</span>
    <label className="cinema-check"><input type="checkbox" checked={take.approved} onChange={e => void action(() => patchTake(take.id, { approved: e.target.checked }))} />QC đạt: danh tính, chuyển động, âm thanh, nội dung</label>
    <label className="cinema-check"><input type="checkbox" checked={!!take.inEdit} onChange={e => void action(() => patchTake(take.id, { inEdit: e.target.checked }))} />Dùng take này trong bản dựng</label>
    <label>Thứ tự take trong cảnh<input className="input" type="number" min="1" value={take.editOrder || 1} onChange={e => { const order = Number(e.target.value); if (Number.isInteger(order) && order > 0) void action(() => patchTake(take.id, { editOrder: order })); }} /></label>
    <div className="cinema-actions"><button className="button button-small" onClick={() => downloadBlob(take.name + (take.blob.type.includes('webm') ? '.webm' : '.mp4'), take.blob)}>Tải take</button><button className="button button-small" onClick={() => void action(() => deleteTake(take.id))}>Xoá take</button></div>{error && <p role="alert">{error}</p>}
  </div>;
}
export default function WorkflowStudio({ openApi }: { openApi: () => void }) {
  const [workflow, setWorkflow] = useState<Workflow | null>(null);
  const [selected, setSelected] = useState(''); const [mergeId, setMergeId] = useState('');
  const [prompt, setPrompt] = useState(''); const [instruction, setInstruction] = useState('Viết tiếp cảnh kinh dị metro, giữ Daniel và Anna, một hành động chính, camera có chủ đích, âm thanh và thoại rõ; không gore.');
  const [takes, setTakes] = useState<Take[]>([]); const [jobs, setJobs] = useState(readJobs);
  const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [videoModel, setVideoModel] = useState('veo-3.1-lite-generate-preview'); const [duration, setDuration] = useState(8);
  const [useImage, setUseImage] = useState(false); const abort = useRef<AbortController | null>(null);
  const [startImage, setStartImage] = useState<string | null>(null);
  const [movie, setMovie] = useState<Blob | null>(null); const [movieUrl, setMovieUrl] = useState('');
  useEffect(() => { if (!movie) return; const url = URL.createObjectURL(movie); setMovieUrl(url); return () => URL.revokeObjectURL(url); }, [movie]);
  const compiled = useMemo(() => workflow ? compileWorkflow(workflow) : null, [workflow]);
  const shot = compiled?.shots.find(s => s.id === selected);
  const image = workflow?.page.snapshot.nodes.find(n => n.id === shot?.imageNodeId);
  const imageUrl = String(image?.data.imageUrl || '');
  async function refresh(w = workflow) { if (w) try { setTakes(await listTakes(w.page.id)); } catch (e) { setError('Không mở kho video: ' + (e as Error).message); } }
  useEffect(() => { async function init() { try { const saved = localStorage.getItem(WORKFLOW_KEY); setWorkflow(parseWorkflow(saved ? JSON.parse(saved) : await (await fetch('workflows/trang-9.json')).json())); } catch (e) { setError('Không tải workflow: ' + (e as Error).message + '. Có thể nhập lại JSON.'); } } void init(); }, []);
  useEffect(() => { if (!workflow || !compiled) return; if (!compiled.shots.some(s => s.id === selected)) setSelected(compiled.shots[0]?.id || ''); if (!compiled.merges.some(m => m.id === mergeId)) setMergeId(compiled.merges[0]?.id || ''); void refresh(workflow); }, [workflow?.page.id, compiled?.shots.length]);
  useEffect(() => { setPrompt(shot?.prompt || ''); }, [shot?.id, shot?.prompt]);
  useEffect(() => { setStartImage(null); setUseImage(false); }, [shot?.id]);
  function persist(next: Workflow) { localStorage.setItem(WORKFLOW_KEY, JSON.stringify(next)); setWorkflow(next); }
  function saveJobs(next: Job[]) { localStorage.setItem(JOB_KEY, JSON.stringify(next)); setJobs(next); }
  async function task(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function importJson(file?: File) { if (!file) return; await task(async () => { if (file.size > 8000000) throw new Error('Workflow tối đa 8 MB'); const next = parseWorkflow(JSON.parse(await file.text())); for (const n of next.page.snapshot.nodes) if (n.type === 'imageReference') n.data.imagePreviewUrl = n.data.imageUrl; persist(next); setStatus('Đã nhập và kiểm tra node/dây nối.'); }); }
  async function generatePrompt() { if (!workflow || !shot) return; await task(async () => { const result = await callStudio('text', { prompt: `Phim: ${workflow.page.name}\nContinuity: ${workflow.page.context || 'Giữ nhân vật, bối cảnh và đạo cụ đã định nghĩa trong prompt nguồn; không thêm nhân vật ngoài chỉ đạo.'}\nPrompt mẫu: ${compiled?.shots.find(s => s.prompt)?.prompt || ''}\nCảnh: ${shot.name}; mục tiêu ${shot.duration}s.\nChỉ đạo: ${instruction}\nPrompt hiện tại: ${prompt}\nChỉ trả prompt video hoàn chỉnh, rõ hành động, ánh sáng, camera, âm thanh và continuity.`, system: 'Bạn là biên kịch và đạo diễn điện ảnh. Viết prompt quay cảnh, không tuyên bố đã tạo video. Không tự bịa nguồn hoặc kết quả.' }); persist(updatePrompt(workflow, shot.id, result.text)); setStatus('Đã viết prompt bằng ' + result.provider + '/' + result.model); }); }
  async function generateVideo() { if (!workflow || !shot) return; await task(async () => {
    if (!prompt.trim()) throw new Error('Bổ sung prompt trước khi tạo video');
    const s = getApiSession(); if (s.provider !== 'google') throw new Error('Chọn Google trong API để tạo Veo. GPT/Claude/gateway hiện dùng văn bản.');
    if (!s.allowPaid) throw new Error('Veo không có free tier. Bật cho phép credit / trả phí trong API.');
    if (jobs.some(j => j.workflowId === workflow.page.id && j.shotId === shot.id && !j.done)) throw new Error('Cảnh có job đang chờ. Kiểm tra trước khi tạo thêm.');
    let reference: string | undefined;
    if (startImage) reference = startImage;
    else if (useImage && imageUrl) reference = await imageForApi(await (await fetch(imageUrl)).blob());
    persist(updatePrompt(workflow, shot.id, prompt));
    const result = await callStudio('video-start', { model: videoModel, prompt, negativePrompt: shot.negativePrompt, duration, aspectRatio: shot.aspectRatio, image: reference });
    saveJobs([...jobs, { id: crypto.randomUUID(), workflowId: workflow.page.id, shotId: shot.id, operation: result.operation, model: videoModel, prompt, createdAt: Date.now() }]); setStatus('Google đã nhận job. Kiểm tra sau khoảng 10–30 giây; không gửi lại tạo video.');
  }); }
  async function checkJob(job: Job) { await task(async () => { if (getApiSession().provider !== 'google') throw new Error('Chọn Google và đúng key đã tạo job'); const result = await callStudio('video-poll', { operation: job.operation }); saveJobs(jobs.map(j => j.id === job.id ? { ...j, done: result.done, uri: result.uri } : j)); setStatus(result.done ? result.uri ? 'Video sẵn sàng. Tải vào kho take để duyệt.' : 'Job kết thúc nhưng không có video; kiểm tra safety filter.' : 'Job đang chạy; có thể kiểm tra lại sau bằng đúng key.'); }); }
  async function downloadJob(job: Job) { if (!job.uri || !workflow) return; await task(async () => { const blob = await callStudio('video-download', { uri: job.uri }); await saveTake({ id: job.id, shotId: job.shotId, workflowId: job.workflowId, blob, name: `veo-${job.id.slice(0, 8)}`, createdAt: Date.now(), approved: false, duration: await videoDuration(blob), provider: 'Google/' + job.model }); await refresh(); setStatus('Đã lưu video thật vào kho take.'); }); }
  async function importClip(file?: File) { if (!file || !workflow || !shot) return; await task(async () => { if (file.size > 200000000) throw new Error('Mỗi clip tối đa 200 MB'); await saveTake({ id: crypto.randomUUID(), workflowId: workflow.page.id, shotId: shot.id, name: file.name, blob: file, createdAt: Date.now(), approved: false, duration: await videoDuration(file), provider: 'Clip nhập' }); await refresh(); setStatus('Đã nhập clip thật; duyệt QC trước khi ghép.'); }); }
  const merge = compiled?.merges.find(m => m.id === mergeId);
  const edit = buildEditPlan(merge?.shots || [], compiled?.shots || [], takes);
  async function render() { await task(async () => { if (!edit.ready) throw new Error('Chọn đủ take QC đạt để đáp ứng thời lượng mỗi cảnh'); abort.current = new AbortController(); try { setMovie(await renderMovie(edit.sequence, setStatus, abort.current.signal, compiled?.shots.find(s => s.id === merge?.shots[0])?.aspectRatio)); setStatus('Đã dựng phim WebM. Xem thử và bấm tải bản dựng.'); } finally { abort.current = null; } }); }
  function exportPackage() { if (!workflow) return; const clean = { ...workflow, takes: takes.map(({ blob, ...metadata }) => ({ ...metadata, bytes: blob.size })), jobs: jobs.filter(j => j.workflowId === workflow.page.id).map(({ uri, ...metadata }) => metadata) }; downloadBlob('director-workflow-package.json', new Blob([JSON.stringify(clean, null, 2)], { type: 'application/json' })); }
  return <section className="cinema-section">
    <div className="cinema-heading"><div><div className="cinema-eyebrow">WORKFLOW ĐIỆN ẢNH · TRANG 9</div><h1>Từ ý tưởng đến từng thước phim.</h1><p>Giữ nhân vật, đạo diễn cảnh, chọn take và ghép theo dây nối.</p></div><button className="button button-primary" onClick={openApi}>Kết nối API ↗</button></div>
    <div className="cinema-actions"><label className="button">Nhập workflow JSON<input className="cinema-file" type="file" accept=".json" disabled={busy} onChange={e => { void importJson(e.target.files?.[0]); e.target.value = ''; }} /></label><button className="button" disabled={!workflow} onClick={exportPackage}>Xuất workflow & metadata</button><button className="button" disabled={!workflow} onClick={() => workflow && downloadBlob('director-workflow-handoff.md', new Blob([workflowHandoff(workflow)], { type: 'text/markdown' }))}>Xuất bàn giao đạo diễn</button></div>
    {error && <div role="alert" className="cinema-alert">{error}</div>}{status && <p role="status" className="guide">{status}</p>}
    {workflow && compiled && <><div className="cinema-metrics"><div><strong>{compiled.shots.length}</strong><span>Cảnh nguồn</span></div><div><strong>{compiled.shots.filter(s => s.prompt.trim()).length}</strong><span>Prompt sẵn sàng</span></div><div><strong>{compiled.merges.length}</strong><span>Nhánh ghép</span></div><div><strong>{takes.length}</strong><span>Take trong kho</span></div></div>
      <div className="cinema-workspace"><aside className="card cinema-shot-list"><h2>{workflow.page.name}</h2><p className="text-small">Ảnh → Prompt → Take → QC → Ghép</p>{compiled.shots.map((s, i) => <button key={s.id} disabled={busy} className={`cinema-shot ${selected === s.id ? 'active' : ''}`} onClick={() => setSelected(s.id)}><span>{String(i + 1).padStart(2, '0')}</span><div><strong>{s.name}</strong><small>{s.duration}s · {s.provider} · {s.prompt.trim() ? 'Có prompt' : 'Cần viết prompt'}</small></div><b>{takes.some(t => t.shotId === s.id && t.approved) ? '✓' : '○'}</b></button>)}</aside>
      <div className="cinema-stack">{shot && <div className="card cinema-stack"><div className="cinema-heading"><h2>{shot.name}</h2><span className="cinema-pill">Mục tiêu {shot.duration}s · {shot.aspectRatio}</span></div>
        {imageUrl && <details><summary>Bảng tham chiếu nhân vật & bối cảnh</summary><img className="cinema-reference" src={imageUrl} alt="Bảng tham chiếu gốc Trang 9" /><p className="text-small">Một bảng ảnh; kiểm tra riêng Daniel, Anna, Survivor, Stalker và bối cảnh. Tạo ảnh đầu cảnh riêng để giữ bố cục tốt hơn.</p></details>}
        <label>Prompt quay cảnh<textarea className="input mono" rows={11} value={prompt} disabled={busy} onChange={e => setPrompt(e.target.value)} placeholder="Viết hành động, camera, ánh sáng, âm thanh và continuity cho cảnh còn trống." /></label>
        <div className="cinema-actions"><button className="button" disabled={busy} onClick={() => { try { persist(updatePrompt(workflow, shot.id, prompt)); setStatus('Đã lưu prompt.'); } catch (e) { setError((e as Error).message); } }}>Lưu prompt</button><button className="button" onClick={() => void navigator.clipboard.writeText(prompt).catch(() => setError('Không chép được; hãy chọn và chép văn bản.'))}>Chép prompt</button></div>
        <label>Chỉ đạo cho AI<input className="input" value={instruction} disabled={busy} onChange={e => setInstruction(e.target.value)} /></label><button className="button" disabled={busy} onClick={() => void generatePrompt()}>AI viết / cải thiện prompt</button>
        <div className="cinema-video-settings"><label>Model video<select className="input" value={videoModel} disabled={busy} onChange={e => setVideoModel(e.target.value)}><option value="veo-3.1-lite-generate-preview">Veo 3.1 Lite</option><option value="veo-3.1-fast-generate-preview">Veo 3.1 Fast</option><option value="veo-3.1-generate-preview">Veo 3.1</option></select></label><label>Độ dài take<select className="input" value={duration} disabled={busy} onChange={e => setDuration(Number(e.target.value))}>{[4, 6, 8].map(n => <option key={n} value={n}>{n} giây</option>)}</select></label></div>
        <label className="cinema-check"><input type="checkbox" checked={useImage} disabled={busy || !imageUrl} onChange={e => setUseImage(e.target.checked)} />Dùng bảng gốc làm ảnh đầu video (có thể xuất hiện cả bảng trong clip)</label>
        <label className="button">Nhập ảnh đầu cảnh PNG/JPEG<input className="cinema-file" type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) void task(async () => { setStartImage(await imageForApi(file)); setUseImage(false); setStatus('Ảnh đầu cảnh chỉ giữ trong phiên này; đổi cảnh hoặc tải lại sẽ cần nhập lại.'); }); e.target.value = ''; }} /></label>
        {startImage && <div><img className="cinema-reference" src={startImage} alt="Ảnh đầu cảnh sẽ gửi tới Veo" /><button className="button button-small" disabled={busy} onClick={() => setStartImage(null)}>Bỏ ảnh đầu cảnh</button></div>}
        <div className="cinema-actions"><button className="button button-primary" disabled={busy || !prompt.trim()} onClick={() => void generateVideo()}>Tạo một take Veo · credit / trả phí</button><label className="button">Nhập clip có sẵn<input className="cinema-file" type="file" accept="video/*" disabled={busy} onChange={e => { void importClip(e.target.files?.[0]); e.target.value = ''; }} /></label></div>
        {shot.duration > 8 && <p className="text-small">Cảnh {shot.duration}s cần nhiều take và dựng lại; clip 8s chưa đủ thời lượng mục tiêu.</p>}
        {jobs.filter(j => j.workflowId === workflow.page.id && j.shotId === shot.id).map(j => <div className="guide" key={j.id}><strong>{j.model}</strong><p className="text-small mono">{j.operation}</p><div className="cinema-actions"><button className="button button-small" disabled={busy} onClick={() => void checkJob(j)}>Kiểm tra job</button>{j.uri && <button className="button button-small" disabled={busy} onClick={() => void downloadJob(j)}>Lưu video vào kho take</button>}<button className="button button-small" disabled={busy} onClick={() => { saveJobs(jobs.filter(x => x.id !== j.id)); setStatus('Bỏ theo dõi không hủy job tại Google.'); }}>Bỏ theo dõi</button></div></div>)}
      </div>}
      <div className="card cinema-stack"><h2>Kho take của cảnh đang chọn</h2><p className="text-small">Video lưu trong IndexedDB của trình duyệt này. Tải take để sao lưu; JSON chỉ chứa metadata.</p><div className="cinema-takes">{takes.filter(t => t.shotId === selected).map(t => <TakeCard key={t.id} take={t} onUpdate={() => void refresh()} />)}</div></div>
      <div className="card cinema-stack"><h2>Dựng nhánh phim</h2><select className="input" value={mergeId} disabled={busy} onChange={e => setMergeId(e.target.value)}>{compiled.merges.map(m => <option key={m.id} value={m.id}>{m.name} · {m.shots.length} cảnh</option>)}</select><div className="cinema-sequence">{edit.coverage.map((c, i) => <span key={c.id + i} className={`cinema-pill ${c.complete ? 'ready' : ''}`}>{compiled.shots.findIndex(s => s.id === c.id) + 1} · {c.duration.toFixed(1)}/{c.target}s {c.complete ? '✓' : '○'}</span>)}</div><p>{edit.coverage.filter(c => c.complete).length}/{edit.coverage.length} cảnh đủ thời lượng với take QC đạt. Chọn take vào bản dựng và đặt thứ tự trong cảnh; phần dư cuối cảnh tự cắt theo thời lượng mục tiêu.</p><p className="text-small">Cắt thẳng, giữ âm thanh clip, xuất WebM 720p/24fps theo thời gian video. Giữ tab phía trước. Xuất take sang DaVinci/Premiere/CapCut để grading, mix âm và xuất MP4 cuối.</p><div className="cinema-actions"><button className="button button-primary" disabled={busy || !edit.ready} onClick={() => void render()}>Ghép & tải phim WebM · miễn phí</button>{busy && abort.current && <button className="button" onClick={() => abort.current?.abort()}>Hủy dựng phim</button>}</div></div>
      {movieUrl && <div className="card cinema-stack"><h2>Bản dựng hoàn thành</h2><video style={{ width: '100%' }} controls src={movieUrl} /><a className="button button-primary" href={movieUrl} download="director-movie.webm">Tải bản dựng WebM</a><p className="text-small">Lưu video trước khi đóng hoặc tải lại tab.</p></div>}
      <details className="card"><summary>Audit workflow · {compiled.warnings.length} điểm cần xử lý</summary><ul>{compiled.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul><p>Dola/Seedance giữ làm thông tin nguồn; cần adapter chính thức để chạy.</p></details>
    </div></div></>}
  </section>;
}
