// Platform-owned by Type. Import appData from this module; do not edit this file.
import type { MutationCtx, QueryCtx } from "./_generated/server";
import { ConvexError } from "convex/values";

type AppDataObject = object;

export type AppDataDocument<
  Data extends AppDataObject = Record<string, unknown>,
> = {
  id: string;
  data: Data;
  version: number;
  createdAt: number;
  updatedAt: number;
};

type StoredAppDataDocument = {
  docId: string;
  data: unknown;
  version: number;
  createdAt: number;
  updatedAt: number;
};

const COLLECTION_PATTERN = /^[a-z0-9_-]{1,64}$/;
const DOCUMENT_ID_PATTERN = /^[A-Za-z0-9_.:-]{1,128}$/;
const MAX_LIST_DOCUMENTS = 200;
const MAX_SERIALIZED_DATA_LENGTH = 64000;
const RUNTIME_MIGRATION_ID = "type_app_runtime";
const FORBIDDEN_DATA_KEYS = new Set(["__proto__", "constructor", "prototype"]);

function fail(code: string): never {
  throw new ConvexError({ code });
}

function validateDocumentId(id: string): void {
  if (!DOCUMENT_ID_PATTERN.test(id)) fail("APP_DATA_INVALID_DOCUMENT_ID");
}

function validateData(data: AppDataObject): void {
  if (data === null || Array.isArray(data) || typeof data !== "object") {
    fail("APP_DATA_INVALID_DOCUMENT");
  }
  if (Object.keys(data).some((key) => FORBIDDEN_DATA_KEYS.has(key))) {
    fail("APP_DATA_INVALID_DOCUMENT");
  }
  let serialized: string | undefined;
  try {
    serialized = JSON.stringify(data);
  } catch {
    fail("APP_DATA_INVALID_DOCUMENT");
  }
  if (
    typeof serialized !== "string" ||
    serialized.length > MAX_SERIALIZED_DATA_LENGTH
  ) {
    fail("APP_DATA_DOCUMENT_TOO_LARGE");
  }
}

function present<Data extends AppDataObject>(
  document: StoredAppDataDocument,
): AppDataDocument<Data> {
  return {
    id: document.docId,
    data: document.data as Data,
    version: document.version,
    createdAt: document.createdAt,
    updatedAt: document.updatedAt,
  };
}

function collection<
  Data extends AppDataObject = Record<string, unknown>,
>(name: string) {
  if (!COLLECTION_PATTERN.test(name)) fail("APP_DATA_INVALID_COLLECTION");

  return {
    async list(
      ctx: QueryCtx,
      options: { limit?: number } = {},
    ): Promise<AppDataDocument<Data>[]> {
      const requestedLimit = options.limit ?? MAX_LIST_DOCUMENTS;
      if (!Number.isFinite(requestedLimit)) fail("APP_DATA_INVALID_LIMIT");
      const limit = Math.min(
        MAX_LIST_DOCUMENTS,
        Math.max(1, Math.trunc(requestedLimit)),
      );
      const documents = await ctx.db
        .query("typeLegacyDocuments")
        .withIndex("by_collection", (query) => query.eq("collection", name))
        .order("asc")
        .take(limit);
      return documents.map((document) => present<Data>(document));
    },

    async get(
      ctx: QueryCtx,
      id: string,
    ): Promise<AppDataDocument<Data> | null> {
      validateDocumentId(id);
      const document = await ctx.db
        .query("typeLegacyDocuments")
        .withIndex("by_collection_doc", (query) =>
          query.eq("collection", name).eq("docId", id),
        )
        .unique();
      return document === null ? null : present<Data>(document);
    },

    async insert(
      ctx: MutationCtx,
      data: Data,
      options: { id?: string } = {},
    ): Promise<AppDataDocument<Data>> {
      const id = options.id ?? crypto.randomUUID();
      validateDocumentId(id);
      validateData(data);
      const existing = await ctx.db
        .query("typeLegacyDocuments")
        .withIndex("by_collection_doc", (query) =>
          query.eq("collection", name).eq("docId", id),
        )
        .unique();
      if (existing !== null) fail("APP_DATA_CONFLICT");
      const now = Date.now();
      await ctx.db.insert("typeLegacyDocuments", {
        migrationId: RUNTIME_MIGRATION_ID,
        collection: name,
        docId: id,
        data,
        version: 1,
        createdAt: now,
        updatedAt: now,
      });
      return { id, data, version: 1, createdAt: now, updatedAt: now };
    },

    async update(
      ctx: MutationCtx,
      id: string,
      data: Data,
      options: { expectedVersion?: number } = {},
    ): Promise<AppDataDocument<Data>> {
      validateDocumentId(id);
      validateData(data);
      if (
        options.expectedVersion !== undefined &&
        (!Number.isInteger(options.expectedVersion) ||
          options.expectedVersion <= 0)
      ) {
        fail("APP_DATA_INVALID_VERSION");
      }
      const existing = await ctx.db
        .query("typeLegacyDocuments")
        .withIndex("by_collection_doc", (query) =>
          query.eq("collection", name).eq("docId", id),
        )
        .unique();
      if (existing === null) fail("APP_DATA_NOT_FOUND");
      if (
        options.expectedVersion !== undefined &&
        options.expectedVersion !== existing.version
      ) {
        fail("APP_DATA_CONFLICT");
      }
      const updatedAt = Date.now();
      const version = existing.version + 1;
      await ctx.db.patch(existing._id, { data, updatedAt, version });
      return {
        id,
        data,
        version,
        createdAt: existing.createdAt,
        updatedAt,
      };
    },

    async delete(
      ctx: MutationCtx,
      id: string,
    ): Promise<AppDataDocument<Data>> {
      validateDocumentId(id);
      const existing = await ctx.db
        .query("typeLegacyDocuments")
        .withIndex("by_collection_doc", (query) =>
          query.eq("collection", name).eq("docId", id),
        )
        .unique();
      if (existing === null) fail("APP_DATA_NOT_FOUND");
      await ctx.db.delete(existing._id);
      return present<Data>(existing);
    },
  };
}

export const appData = { collection };
