import { build } from 'esbuild';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
const folder = await mkdtemp(join(tmpdir(), 'director-workflow-'));
try {
  const workflowModule = join(folder, 'workflow.mjs'), editModule = join(folder, 'edit.mjs');
  await build({ entryPoints: ['shared/workflow.ts'], outfile: workflowModule, platform: 'node', format: 'esm', bundle: true });
  await build({ entryPoints: ['shared/editPlan.ts'], outfile: editModule, platform: 'node', format: 'esm', bundle: true });
  const { parseWorkflow, compileWorkflow, updatePrompt, workflowHandoff } = await import(pathToFileURL(workflowModule));
  const { buildEditPlan } = await import(pathToFileURL(editModule));
  const raw = await readFile(resolve('../../workflow-page-Trang-9-2026-10-03.json'));
  const source = JSON.parse(raw);
  const normalized = JSON.parse(await readFile('public/workflows/trang-9.json'));
  assert.equal(normalized.source.sha256, createHash('sha256').update(raw).digest('hex'));
  const w = parseWorkflow(normalized), c = compileWorkflow(w);
  assert.equal(w.page.snapshot.nodes.length, 57); assert.equal(w.page.snapshot.edges.length, 78);
  assert.equal(c.shots.length, 26); assert.equal(c.shots.filter(s => s.prompt.trim()).length, 1);
  assert.deepEqual(c.merges.map(m => m.shots.length), [20, 6]);
  assert.deepEqual(c.merges.map(m => m.shots), source.page.snapshot.nodes.filter(n => n.type === 'videoMerge').map(n => source.page.snapshot.edges.filter(e => e.target === n.id).map(e => e.source)));
  assert.equal(c.shots.slice(0, 20).reduce((n, s) => n + s.duration, 0), 600);
  assert.equal(c.shots.slice(20).reduce((n, s) => n + s.duration, 0), 48);
  console.log('PASS source hash, all nodes/edges, 26 scenes, 600s/48s and exact merge order');
  const changed = updatePrompt(w, c.shots[1].id, 'A new scene');
  assert.equal(compileWorkflow(changed).shots[1].prompt, 'A new scene'); assert.equal(c.shots[1].prompt, '');
  assert.ok(workflowHandoff(w).includes('CHƯA CÓ PROMPT'));
  console.log('PASS editable prompt with source immutability and handoff');
  const forged = structuredClone(w); forged.page.snapshot.edges.push({ id: 'bad', source: c.merges[0].id, target: c.merges[0].id });
  assert.throws(() => parseWorkflow(forged), /vòng lặp/);
  const bad = structuredClone(w); bad.page.snapshot.edges[0].source = 'missing'; assert.throws(() => parseWorkflow(bad), /không tồn tại/);
  const keyDoc = structuredClone(w); keyDoc.apiKey = 'fake-secret'; keyDoc.page.snapshot.nodes[0].data.apiKey = 'fake-secret'; assert.ok(!JSON.stringify(parseWorkflow(keyDoc)).includes('fake-secret'));
  const external = structuredClone(w); external.page.snapshot.nodes.find(n => n.type === 'imageReference').data.imageUrl = 'https://evil.example/image?key=fake'; assert.throws(() => parseWorkflow(external), /Ảnh phải/);
  console.log('PASS graph validation, cycles, dangling wires, key stripping and external image rejection');
  const takes = Array.from({ length: 4 }, (_, i) => ({ id: 't' + i, shotId: 's', approved: true, inEdit: true, duration: 8, createdAt: i, editOrder: i + 1 }));
  const plan = buildEditPlan(['s'], [{ id: 's', duration: 30 }], takes);
  assert.ok(plan.ready); assert.equal(plan.sequence.length, 4); assert.equal(plan.sequence[3].outPoint, 6); assert.equal(plan.coverage[0].duration, 30);
  assert.equal(buildEditPlan(['s'], [{ id: 's', duration: 30 }], takes.slice(0, 3)).ready, false);
  assert.equal(buildEditPlan(['s'], [{ id: 's', duration: 30 }], takes.map(t => ({ ...t, approved: false }))).ready, false);
  assert.equal(buildEditPlan(['s'], [{ id: 's', duration: 30 }], takes.map(t => ({ ...t, inEdit: false }))).ready, false);
  console.log('PASS multi-take 30s assembly, trim, insufficient coverage and QC gating');
  const projectModule = join(folder, 'project.mjs'), productionModule = join(folder, 'production.mjs');
  await build({ entryPoints: ['shared/projectWorkflow.ts'], outfile: projectModule, platform: 'node', format: 'esm', bundle: true });
  await build({ entryPoints: ['shared/production.ts'], outfile: productionModule, platform: 'node', format: 'esm', bundle: true });
  const { projectToWorkflow } = await import(pathToFileURL(projectModule));
  const { standardScenes } = await import(pathToFileURL(productionModule));
  const sourceScenes = standardScenes(60).map((s, i) => ({ ...s, _id: `s${i}`, projectId: 'p1', _creationTime: 0 }));
  const linked = projectToWorkflow({ _id: 'p1', title: 'Source project', characterBible: 'Fictional director character', format: 'standard' }, sourceScenes, null);
  const linkedPlan = compileWorkflow(linked);
  assert.equal(linkedPlan.shots.length, sourceScenes.length);
  assert.equal(linkedPlan.shots.reduce((n, s) => n + s.duration, 0), 60);
  assert.ok(linkedPlan.shots[0].prompt.includes('Fictional director character'));
  assert.equal(linkedPlan.shots[0].aspectRatio, '9:16');
  assert.deepEqual(linkedPlan.merges[0].shots, sourceScenes.map(s => 'video-' + s._id));
  console.log('PASS production board bridges to workflow without losing scenes, timing, bible or portrait format');
} finally { await rm(folder, { recursive: true, force: true }); }
